<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="MAIN" Id="{b180a901-9060-4304-b58a-988ceafe4550}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbFoo1	:	MyNamespace01.FB_Foo;
	fbFoo2	:	MyNamespace02.FB_Foo;
	fbFoo3	:	FB_Foo;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFoo1();
fbFoo2();
fbFoo3();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>